### ISSUE TITLE
403 (forbidden) for some SLES-Repos from SCC with Katello 3.18.5 and Foreman 2.3.5

### ISSUE THREAD

**Issue by thomas-merz** [ATIX-AG/foreman_scc_manager#100]
We had this problem first time starting on Oct, 1st 2021 and fixed it on Dec, 17th 2021 after wasting much time with SUSE support but by fixing some Upstream URLs regarding the right (a new!?) "token" for some (5-10) repos. But now we have this problem since May 2dn, 2022 again - but this time for about 80+ SLES-Repos 😢 

For example:
> Errors:
403, message='Forbidden', url=URL('https://updates.suse.com/SUSE/Products/SLE-Module-Development-Tools/15-SP2/x86_64/product_source/?---token---')

Does anyone else have this problem?
Does anyone know how to fix if effeciently (not by hand!)?
Is the root cause already fixed with a newer Katello version?
Does anyone know if/why SUSE may be changing every 6 months some repo-URLs/tokens?

Fixing the Repo URL with a new/valid token solves this problem. But to get this new URL for each repo one must add another SCC Acount with the same credentials and select (only) the failing ~80+ repos and after waiting until something is finnished: click on them to get the new URL and copy&paste it into the failing repos.

**Comment by nadjaheitmann** [comment]
Sorry to hear that. Which SCC manager version are you at?

**Comment by marco-endres** [comment]
Hi @nadjaheitmann,

we use following scc Version 1.8.10-1.

`tfm-rubygem-foreman_scc_manager-1.8.10-1.fm2_3.el7.noarch`

**Comment by nadjaheitmann** [comment]
I think your should start by upgrading your SCC manager version. There was a problem with updating the token in one of the older version which has been fixed in the meantime.

**Comment by thomasmerz** [comment]
We could fix it by applying [this patch](https://github.com/ATIX-AG/foreman_scc_manager/commit/5e4bbcbc622a8a6ac893ad585f00d1f6df4177c7) to our installation and re-sync our SCC account 👍🏼  No need to upgrade full-stack of Foreman, Katello and SCC plugin… But many thanks for your "hint" 😃 
So issue can be closed - we have noticed, that we really should (and are already planning/preparing) upgrading our stack.

**Comment by thomas-merz** [comment]
We could fix it by applying [this patch](https://github.com/ATIX-AG/foreman_scc_manager/commit/5e4bbcbc622a8a6ac893ad585f00d1f6df4177c7) to our installation and re-sync our SCC account 👍🏼 No need to upgrade full-stack of Foreman, Katello and SCC plugin… But many thanks for your "hint" 😃
So issue can be closed - we have noticed, that we really should (and are already planning/preparing) upgrading our stack.
