### ISSUE TITLE
Link breaked and Missing web page 

### ISSUE THREAD

**Issue by mipsou** [ATIX-AG/foreman_scc_manager#112]
![image](https://user-images.githubusercontent.com/5244347/198083344-c09ba9c8-1195-4697-b267-399767c80f62.png)

**Comment by quba42** [comment]
Links in the orcharhino documentation are not guaranteed to be stable, I believe this section has moved here:
https://docs.orcharhino.com/or/docs/sources/guides/suse_linux_enterprise_server/managing_content/managing_suse_content.html#Installing_the_SCC_Manager_Plugin_content-management

In general, I recommend using the documentations search functionality in such cases!

**Comment by maximiliankolb** [comment]
Thank you @mipsou for reporting this. I already have an open PR: https://github.com/ATIX-AG/foreman_scc_manager/pull/108 

I recommend you have a look at [Managing SUSE Content](https://docs.orcharhino.com/or/docs/sources/guides/suse_linux_enterprise_server/managing_content/managing_suse_content.html) as part of the SLES guide within orcharhino documentatation.

**Comment by nadjaheitmann** [comment]
#108 was already merged
