### ISSUE TITLE
Add product button not active (again)

### ISSUE THREAD

**Issue by nadjaheitmann** [ATIX-AG/foreman_scc_manager#119]
This has already been addressed by #105 but the issue seems to reappear in Foreman 3.6

**Comment by nadjaheitmann** [comment]
@SupremeGit I was looking into this but it is a bit hard to track because the error is only occurring in production environment but not in development environment. Still on it.

**Comment by SupremeGit** [comment]
Many thanks for your efforts, it's such a frustrating bug, I've got a new foreman/katello installation which is working perfectly, way better than earlier versions I've tried - but I can't mirror any SLES content, until this issue is fixed :-(

**Comment by nadjaheitmann** [comment]
I can totally understand that. You could try the hammer plugin of scc manager for now. Now sure if that works, though. Might need some bug fixing as well.

**Comment by SupremeGit** [comment]
Aah thanks Nadja & Bernhard. I will see if i can get the fixed SCC plugin & give that a go, or if its not available yet i will try the hammer.

**Comment by nadjaheitmann** [comment]
@SupremeGit The packaging PR is still pending, unfortunately, so the package is not yet available. Fingers crossed that it will be merged, soon :crossed_fingers:

**Comment by nadjaheitmann** [comment]
The PR just got merged, but it will take a bit until the package becomes available. I also need to cherry-pick it to Foreman 3.6 . You can check here for the 2.3.0 package https://yum.theforeman.org/katello/nightly/katello/el8/x86_64/ , it will be available, eventually.

**Comment by nadjaheitmann** [comment]
@SupremeGit You can install this package https://yum.theforeman.org/katello/nightly/katello/el8/x86_64/rubygem-foreman_scc_manager-2.3.0-1.fm3_8.el8.noarch.rpm . The button should work now.

**Comment by SupremeGit** [comment]
Eeeeeeeet worx!

Thank you Nadja, when installing i got error about missing dependency for doc package, but no problem, i've mashed in the above rpm using --nodeps, so i have an outdated doc rpm now but who cares, that can update itself when updated doc rpm find its way into repos.

So i have now been able to select Suse products and get them syncing :-)

Eeexccellent :-)
And many TY again for handling this issue like a true professional :-)
