### ISSUE TITLE
Not working with foreman-1.24.2 and Katello-3.14.1

### ISSUE THREAD

**Issue by mallmaluss** [ATIX-AG/foreman_scc_manager#36]
When synchronizing with SCC through a proxy server, the task fails.

Action:
Actions::SccManager::Sync
Input:
{"scc_account"=>{"id"=>2, "name"=>"suse"},
 "repo_status"=>"FAILURE",
 "prod_status"=>"FAILURE",
 "current_request_id"=>nil,
 "current_timezone"=>"USA",
 "current_user_id"=>4,
 "current_organization_id"=>1,
 "current_location_id"=>2}
Output:
{}
Exception:
RuntimeError: Updating failed

**Comment by sbernhard** [comment]
which  scc version are you using?

**Comment by mallmaluss** [comment]
Available in the Catello repository - 1.7.0

I manually updated the plug-ins to version 1.8.0, the problem was fixed.


________________________________
От: Bernhard Suttner <notifications@github.com>
Отправлено: 6 апреля 2020 г. 10:21
Кому: ATIX-AG/foreman_scc_manager
Копия: Стружкин Андрей Юрьевич; Author
Тема: Re: [ATIX-AG/foreman_scc_manager] Not working with foreman-1.24.2 and Katello-3.14.1 (#36)


which scc version are you using?

**Comment by mallmaluss** [comment]
close
