### ISSUE TITLE
Do not sync debuginfo and source rpms by default

### ISSUE THREAD

**Issue by dgoetz** [ATIX-AG/foreman_scc_manager#37]
SUSE does not differentiate between debuginfo, source and normal repositories in their products. So if you select a product it will make all repositories available. Furthermore in some normal repositories are also source rpms included. If you sync this by default you will need a big amount of disk space and traffic for commonly not used packages.

It would be great to not have this by default. So selecting a product should not include the debuginfo and source repositories while normal repositories are created with Ignorable Content set to Source RPM.

If you think this is a too big change in behaviour, having a setting to switch between both options would be good. I would default then to not include the unnecessary content, but could totally understand keeping the old behaviour as default.

Also to mention is if you delete the unwanted repositories it seems like there is no way to re-add them at the moment.

**Comment by sbernhard** [comment]
Thanks for the report Dirk. 

To be honest, we have this topic on our roadmap :) We are planning to be able to select which repository a user want to create. Currently, all repositories of a product are created. This would also solve the issue, that additional repositories of a product are added later on or would be deleted.

**Comment by nadjaheitmann** [comment]
This was addressed in #85 . We are happy about test reports :)
