### ISSUE TITLE
foreman 2.0/katello 3.16 and scc manager plugin

### ISSUE THREAD

**Issue by mkd808** [ATIX-AG/foreman_scc_manager#41]
Getting the following error message on this install.

katello-3.15.0.1-1.el7.noarch

Oops, we're sorry but something went wrong PG::UndefinedTable: ERROR: relation "scc_accounts" does not exist LINE 1: SELECT "scc_accounts".* FROM "scc_accounts" ORDER BY "scc_a... ^ : SELECT "scc_accounts".* FROM "scc_accounts" ORDER BY "scc_accounts"."login" ASC LIMIT $1 OFFSET $2

**Comment by mkd808** [comment]
Resolved with Yum update. Reboot

Service unavailable ERF64-6496 [Foreman::MaintenanceException]: There are migrations pending in the system.

Continue any pending database migrations with #foreman-rake db:migrate

foreman-maintain service stop / start

**Comment by m-bucher** [comment]
Glad you could solve the issue yourself.
One note though: I think normally you can run `foreman-installer` without any arguments after `yum install <plugin>` to make sure DB-migrations and -seeds have been applied and the services are restarted.
