### ISSUE TITLE
DB-migration fails with Katello 4.2

### ISSUE THREAD

**Issue by m-bucher** [ATIX-AG/foreman_scc_manager#77]
Katello has changed `Katello::GpgKey` model to `Katello::ContentCredential` as well as the underlying DB-table (https://github.com/Katello/katello/commit/82c3516ab71ac773bff195683879b380e2bbe4f6).

This means one of our migration fails with `PG::UndefinedTable: ERROR:  relation "katello_gpg_keys" does not exist`
[/db/migrate/20201119084201_add_gpg_key_to_scc_account.rb](https://github.com/ATIX-AG/foreman_scc_manager/blob/master/db/migrate/20201119084201_add_gpg_key_to_scc_account.rb)

**Comment by omega949** [comment]
Hi.
   I am facing this issue myself today, is there a quick or should i just use the older version of katello/foreman for now?

Thanks

**Comment by m-bucher** [comment]
@omega949 I opened a Draft-PR, which should fix the issue for Katello>=4.2.
Not sure if this will be the final solution, but if you want to test it, please do :smiley:
